-- MySQL Script generated by MySQL Workbench
-- Tue Dec 17 03:07:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corrida
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `corrida` ;

-- -----------------------------------------------------
-- Schema corrida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corrida` DEFAULT CHARACTER SET utf8 ;
USE `corrida` ;

-- -----------------------------------------------------
-- Table `corrida`.`Kart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corrida`.`Kart` ;

CREATE TABLE IF NOT EXISTS `corrida`.`Kart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Hora` VARCHAR(45) NOT NULL,
  `Piloto` VARCHAR(45) NOT NULL,
  `Volta` INT NOT NULL,
  `Tempo` VARCHAR(45) NOT NULL,
  `Velocidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from kart